export const paOptions = [
  { value: "PA-28", label: "PA-28" },
  { value: "DA-42", label: "DA-42" }
];

export const aircraftOptions = [
  { value: "VT-BBS", label: "VT-BBS" },
  { value: "VT-CEO", label: "VT-CEO" },
  { value: "VT-SSP", label: "VT-SSP" },
  { value: "VT-SSQ", label: "VT-SSQ" },
  { value: "VT-SST", label: "VT-SST" },
  { value: "VT-SSU", label: "VT-SSU" },
  { value: "VT-SSV", label: "VT-SSV" },
  { value: "VT-SSW", label: "VT-SSW" },
  { value: "VT-SSY", label: "VT-SSY" },
  { value: "VT-SSZ", label: "VT-SSZ" },
  { value: "VT-SSX", label: "VT-SSX" },
];

// ------------------------INSTRUCTORS------------------------

export const instructors = [
  { value: "SHARIQ ALI", label: "SHARIQ ALI" },
  { value: "RUSHIKESH VIKAS JALKOTE", label: "RUSHIKESH VIKAS JALKOTE" },
  { value: "PANKHURI SAXENA", label: "PANKHURI SAXENA" },
  { value: "SURYANSH MISHRA", label: "SURYANSH MISHRA" },
  { value: "DIGVIJAY SHEKHAWAT", label: "DIGVIJAY SHEKHAWAT" },
  { value: "KV TARUN", label: "KV TARUN" },
  { value: "FAHAD KHAN", label: "FAHAD KHAN" },
  { value: "ARFIN", label: "ARFIN" },
  { value: "AYUSH RAJ", label: "AYUSH RAJ" },
  { value: "MOHAK PARMAR", label: "MOHAK PARMAR" },
  { value: "PARTH MISHRA", label: "PARTH MISHRA" },
  { value: "JEROME PAUL", label: "JEROME PAUL" },
  { value: "ASHUTOSH SHARMA", label: "ASHUTOSH SHARMA" },
  { value: "TAPAN KUMAR", label: "TAPAN KUMAR" },
  { value: "TANISH KASWAN", label: "TANISH KASWAN" },
  { value: "GURYOG SINGH", label: "GURYOG SINGH" },
  { value: "YUVRAJ DASHORA", label: "YUVRAJ DASHORA" },
  { value: "JATIN GHANGAS", label: "JATIN GHANGAS" },
  { value: "SIDDHI POOJARY", label: "SIDDHI POOJARY" },
  { value: "SURESH KAURANI", label: "SURESH KAURANI" },

  // =========================STUDENTS===========================
  // Batch 1
  { value: "ANIRUDH BORA", label: "ANIRUDH BORA", batch: "1" },
  { value: "APEKSHA SHARMA", label: "APEKSHA SHARMA", batch: "1" },
  { value: "BHARGAVI BHARDWAJ", label: "BHARGAVI BHARDWAJ", batch: "1" },
  { value: "DEVANSH SINGH BAIS", label: "DEVANSH SINGH BAIS", batch: "1" },
  { value: "DILSHAD NAVSHAD IDRISI", label: "DILSHAD NAVSHAD IDRISI", batch: "1" },
  { value: "DRISHA MODI", label: "DRISHA MODI", batch: "1" },
  { value: "GOURAV GAUTAM", label: "GOURAV GAUTAM", batch: "1" },
  { value: "HARDIK AGARWAL", label: "HARDIK AGARWAL", batch: "1" },
  { value: "HARSHITA BATRA", label: "HARSHITA BATRA", batch: "1" },
  { value: "HARSHITA NARU", label: "HARSHITA NARU", batch: "1" },
  { value: "ISHITA BHARDWAJ", label: "ISHITA BHARDWAJ", batch: "1" },
  { value: "JAI DEV PRATAP SINGH", label: "JAI DEV PRATAP SINGH", batch: "1" },
  { value: "JANVI BALWANI", label: "JANVI BALWANI", batch: "1" },
  { value: "JEREMY JOHN", label: "JEREMY JOHN", batch: "1" },
  { value: "KASHISH SANTOSH CHAUDHARY", label: "KASHISH SANTOSH CHAUDHARY", batch: "1" },
  { value: "LAKSHYA SETHI", label: "LAKSHYA SETHI", batch: "1" },
  { value: "MANSI CHOUDHARY", label: "MANSI CHOUDHARY", batch: "1" },
  { value: "NIKHIL SHARMA", label: "NIKHIL SHARMA", batch: "1" },
  { value: "OM ARORA", label: "OM ARORA", batch: "1" },
  { value: "PARTH PAPNEJA", label: "PARTH PAPNEJA", batch: "1" },
  { value: "PRACHI GUPTA", label: "PRACHI GUPTA", batch: "1" },
  { value: "PREM KUMAR", label: "PREM KUMAR", batch: "1" },
  { value: "PRIYANSHI YADAV", label: "PRIYANSHI YADAV", batch: "1" },
  { value: "PURUHANS", label: "PURUHANS", batch: "1" },
  { value: "PURVANSHI GUPTA", label: "PURVANSHI GUPTA", batch: "1" },
  { value: "RISHABH SINDHU", label: "RISHABH SINDHU", batch: "1" },
  { value: "RIYA MANGLANI", label: "RIYA MANGLANI", batch: "1" },
  { value: "ROMIN GOSWAMI", label: "ROMIN GOSWAMI", batch: "1" },
  { value: "SAHIL BACHHAWAT", label: "SAHIL BACHHAWAT", batch: "1" },
  { value: "SAMEER KUMAR YADAV", label: "SAMEER KUMAR YADAV", batch: "1" },
  { value: "SARTAJ GULZAR", label: "SARTAJ GULZAR", batch: "1" },
  { value: "SARTHAK MEHROTRA", label: "SARTHAK MEHROTRA", batch: "1" },
  { value: "SATYAM PESWANI", label: "SATYAM PESWANI", batch: "1" },
  { value: "SHARDUL SETH", label: "SHARDUL SETH", batch: "1" },
  { value: "SHAURYA SINGH", label: "SHAURYA SINGH", batch: "1" },
  { value: "TANISH KASWAN NAYASAR", label: "TANISH KASWAN NAYASAR", batch: "1" },
  { value: "TEJAS BHATIA", label: "TEJAS BHATIA", batch: "1" },
  { value: "TRIJAL KUMAR", label: "TRIJAL KUMAR", batch: "1" },
  { value: "UTKARSH SRIVASTAVA", label: "UTKARSH SRIVASTAVA", batch: "1" },
  { value: "VAIBHAV GARG", label: "VAIBHAV GARG", batch: "1" },
  { value: "VALLABH AMBADAS UMALE", label: "VALLABH AMBADAS UMALE", batch: "1" },
  { value: "VEDANT GYANCHANDANI", label: "VEDANT GYANCHANDANI", batch: "1" },
  { value: "VIJAY SAHU", label: "VIJAY SAHU", batch: "1" },
  { value: "VIVAAN KASHYAP", label: "VIVAAN KASHYAP", batch: "1" },
  { value: "VRINDA JHURIA", label: "VRINDA JHURIA", batch: "1" },

  // Batch 2
  { value: "ABHYUDAY KUMAWAT", label: "ABHYUDAY KUMAWAT", batch: "2" },
  { value: "ADITYA SINGH", label: "ADITYA SINGH", batch: "2" },
  { value: "AMAN AHMED", label: "AMAN AHMED", batch: "2" },
  { value: "ARNAV SETH", label: "ARNAV SETH", batch: "2" },
  { value: "ASMIT RAWAT", label: "ASMIT RAWAT", batch: "2" },
  { value: "AYUSH AJAY", label: "AYUSH AJAY", batch: "2" },
  { value: "DIYA JAIN", label: "DIYA JAIN", batch: "2" },
  { value: "GAURAV KHANNA", label: "GAURAV KHANNA", batch: "2" },
  { value: "JAYNIT JAIN", label: "JAYNIT JAIN", batch: "2" },
  { value: "PRASOON MATHUR", label: "PRASOON MATHUR", batch: "2" },
  { value: "PRIYANSHI KUMAR", label: "PRIYANSHI KUMAR", batch: "2" },
  { value: "RAGHAV DWIVEDI", label: "RAGHAV DWIVEDI", batch: "2" },
  { value: "SANI MALIK", label: "SANI MALIK", batch: "2" },
  { value: "SHRUTI KUMARI", label: "SHRUTI KUMARI", batch: "2" },
  { value: "SNEHA JAUHARI", label: "SNEHA JAUHARI", batch: "2" },
  { value: "TANVEER SINGH ANEJA", label: "TANVEER SINGH ANEJA", batch: "2" },
  // Batch 3
  { value: "ADESH KUMAR YADAV", label: "ADESH KUMAR YADAV", batch: "3" },
  { value: "ANTRA KATOCH", label: "ANTRA KATOCH", batch: "3" },
  { value: "ASHMAN SINGH SANDHU", label: "ASHMAN SINGH SANDHU", batch: "3" },
  { value: "BHANU PRATAP SINGH", label: "BHANU PRATAP SINGH", batch: "3" },
  { value: "BHARAT DHAKAR", label: "BHARAT DHAKAR", batch: "3" },
  { value: "CHAVI SAXENA", label: "CHAVI SAXENA", batch: "3" },
  { value: "DEVEN SHARMA", label: "DEVEN SHARMA", batch: "3" },
  { value: "DISHA THAKKAR", label: "DISHA THAKKAR", batch: "3" },
  { value: "EKLAVYA SINGH", label: "EKLAVYA SINGH", batch: "3" },
  { value: "HIR PATEL", label: "HIR PATEL", batch: "3" },
  { value: "JAYAGANESAN S", label: "JAYAGANESAN S", batch: "3" },
  { value: "NANDAN VACHHANI", label: "NANDAN VACHHANI", batch: "3" },
  { value: "NAVYYA MAKIN", label: "NAVYYA MAKIN", batch: "3" },
  { value: "NIKHIL GOEL", label: "NIKHIL GOEL", batch: "3" },
  { value: "PARV TAYAL", label: "PARV TAYAL", batch: "3" },
  { value: "PRIYANSHU SINGHAL", label: "PRIYANSHU SINGHAL", batch: "3" },
  { value: "RAJAT MEENA", label: "RAJAT MEENA", batch: "3" },
  { value: "RIYA SUTHAR", label: "RIYA SUTHAR", batch: "3" },
  { value: "SAIYAM CHAKRAVERTY", label: "SAIYAM CHAKRAVERTY", batch: "3" },
  { value: "SAMRUDDHA SHETE", label: "SAMRUDDHA SHETE", batch: "3" },
  { value: "SAYONI AGARWAL", label: "SAYONI AGARWAL", batch: "3" },
  { value: "SHIVANI UDAR", label: "SHIVANI UDAR", batch: "3" },
  { value: "SIDNEY FERNANDES", label: "SIDNEY FERNANDES", batch: "3" },
  { value: "TANU PRIYA", label: "TANU PRIYA", batch: "3" },

  // Batch 4
  { value: "AMAN KUMAR DALAL", label: "AMAN KUMAR DALAL", batch: "4" },
  { value: "DIVYANSH", label: "DIVYANSH", batch: "4" },
  { value: "ISHA RATHOD", label: "ISHA RATHOD", batch: "4" },
  { value: "JAI SHARMA", label: "JAI SHARMA", batch: "4" },
  { value: "KESHAV SHARMA", label: "KESHAV SHARMA", batch: "4" },
  { value: "KOMARAVELLI ROSHAN", label: "KOMARAVELLI ROSHAN", batch: "4" },
  { value: "KUNAL CHOUDHARY", label: "KUNAL CHOUDHARY", batch: "4" },
  { value: "MOHD NAWAZ", label: "MOHD NAWAZ", batch: "4" },
  { value: "PARAS RADHENAGAR", label: "PARAS RADHENAGAR", batch: "4" },
  { value: "PREM", label: "PREM", batch: "4" },
  { value: "SAKSHI SOLANKI", label: "SAKSHI SOLANKI", batch: "4" },
  { value: "SANEHI NAYAK", label: "SANEHI NAYAK", batch: "4" },
  { value: "SRUSHTI ABHAY", label: "SRUSHTI ABHAY", batch: "4" },
  { value: "YASH JINDAL", label: "YASH JINDAL", batch: "4" },

  // Batch 5
  { value: "ANJALI ADHIKARI", label: "ANJALI ADHIKARI", batch: "5" },
  { value: "ANSHPREET SINGH", label: "ANSHPREET SINGH", batch: "5" },
  { value: "ANUSH BAGRODIA", label: "ANUSH BAGRODIA", batch: "5" },
  { value: "ARJUN SHUKLA", label: "ARJUN SHUKLA", batch: "5" },
  { value: "GANGA SINGH", label: "GANGA SINGH", batch: "5" },
  { value: "MANAV", label: "MANAV", batch: "5" },
  { value: "MAYANK CHOUDHARY", label: "MAYANK CHOUDHARY", batch: "5" },
  { value: "MAYANK PURI", label: "MAYANK PURI", batch: "5" },
  { value: "RASHI SINGH", label: "RASHI SINGH", batch: "5" },
  { value: "SHASHANK SINGH PARIHAR", label: "SHASHANK SINGH PARIHAR", batch: "5" },
  { value: "SHIVAM MAHAJAN", label: "SHIVAM MAHAJAN", batch: "5" },
  { value: "SOURABH SETHI", label: "SOURABH SETHI", batch: "5" },
  { value: "UBEAID SHAIKH", label: "UBEAID SHAIKH", batch: "5" },
  { value: "YASH YADAV", label: "YASH YADAV", batch: "5" },
  { value: "YASHITA NAGAR", label: "YASHITA NAGAR", batch: "5" },

  // Batch 6
  { value: "AASHTA SHARAMA", label: "AASHTA SHARAMA", batch: "6" },
  { value: "ADIT UPPINI", label: "ADIT UPPINI", batch: "6" },
  { value: "AJEET SINGH", label: "AJEET SINGH", batch: "6" },
  { value: "AKSHAT AGARWAL", label: "AKSHAT AGARWAL", batch: "6" },
  { value: "ARSHPREET", label: "ARSHPREET", batch: "6" },
  { value: "ASHISH BISHNOI", label: "ASHISH BISHNOI", batch: "6" },
  { value: "ATISHAY", label: "ATISHAY", batch: "6" },
  { value: "DAKSHIKA SHARMA", label: "DAKSHIKA SHARMA", batch: "6" },
  { value: "DIVYANSH SINGH", label: "DIVYANSH SINGH", batch: "6" },
  { value: "JAI DESAI", label: "JAI DESAI", batch: "6" },
  { value: "KUNAL MEENA", label: "KUNAL MEENA", batch: "6" },
  { value: "M MANNO GANESAN", label: "M MANNO GANESAN", batch: "6" },
  { value: "MEHAK ARCHRIYA", label: "MEHAK ARCHRIYA", batch: "6" },
  { value: "NIKHIL VAISHNAV", label: "NIKHIL VAISHNAV", batch: "6" },
  { value: "SHRUTI SINGH", label: "SHRUTI SINGH", batch: "6" },
  { value: "SHUBHAM BIST", label: "SHUBHAM BIST", batch: "6" },
  { value: "SUKRIT SINGH", label: "SUKRIT SINGH", batch: "6" },
  { value: "VEDANT MOHAN", label: "VEDANT MOHAN", batch: "6" },
  { value: "VIDHI VIVEK", label: "VIDHI VIVEK", batch: "6" },
  { value: "YAJAT TAK", label: "YAJAT TAK", batch: "6" },

  // Batch 7
  { value: "ANIMESH", label: "ANIMESH", batch: "7" },
  { value: "ARYAMAN", label: "ARYAMAN", batch: "7" },
  { value: "BHARAT", label: "BHARAT", batch: "7" },
  { value: "DIVYANSH KHARI", label: "DIVYANSH KHARI", batch: "7" },
  { value: "DIYA PATEL", label: "DIYA PATEL", batch: "7" },
  { value: "HARDIK WASSON", label: "HARDIK WASSON", batch: "7" },
  { value: "HUSSAIN", label: "HUSSAIN", batch: "7" },
  { value: "JIGYASA", label: "JIGYASA", batch: "7" },
  { value: "KESHIKA CHHETRI", label: "KESHIKA CHHETRI", batch: "7" },
  { value: "KURAPATI MAANVIE", label: "KURAPATI MAANVIE", batch: "7" },
  { value: "MINI SHARMA", label: "MINI SHARMA", batch: "7" },
  { value: "MOHAK", label: "MOHAK", batch: "7" },
  { value: "MOHD KAIS", label: "MOHD KAIS", batch: "7" },
  { value: "PAKSH", label: "PAKSH", batch: "7" },
  { value: "PIYUSH", label: "PIYUSH", batch: "7" },
  { value: "PRABHJOT", label: "PRABHJOT", batch: "7" },
  { value: "RAHUL SHARMA", label: "RAHUL SHARMA", batch: "7" },
  { value: "RASKAR KETAKI", label: "RASKAR KETAKI", batch: "7" },
  { value: "RISHABH SINGH", label: "RISHABH SINGH", batch: "7" },
  { value: "RIYA VATS", label: "RIYA VATS", batch: "7" },
  { value: "RUDRAPRIYA", label: "RUDRAPRIYA", batch: "7" },
  { value: "SANDESH", label: "SANDESH", batch: "7" },
  // Batch 8
  { value: "ANSH PREET BALI", label: "ANSH PREET BALI", batch: "8" },
  { value: "AUSTRAL", label: "AUSTRAL", batch: "8" },
  { value: "JATIN DAGAR", label: "JATIN DAGAR", batch: "8" },
  { value: "MEHUL", label: "MEHUL", batch: "8" },
  { value: "MINAKSHI YADAV", label: "MINAKSHI YADAV", batch: "8" },
  { value: "RADHIKA JAIN", label: "RADHIKA JAIN", batch: "8" },
  { value: "ROHAK JAIN", label: "ROHAK JAIN", batch: "8" },
  { value: "SHUBHAM AGARWAL", label: "SHUBHAM AGARWAL", batch: "8" },
  { value: "VARUN SINHA", label: "VARUN SINHA", batch: "8" },
  { value: "YASH BANSAL", label: "YASH BANSAL", batch: "8" },
  { value: "YASH MISHRA", label: "YASH MISHRA", batch: "8" },

  // Batch 9
  { value: "ANIRUDH SINGH", label: "ANIRUDH SINGH", batch: "9" },
  { value: "ANMOL SINGH", label: "ANMOL SINGH", batch: "9" },
  { value: "AYUSH WABLE", label: "AYUSH WABLE", batch: "9" },
  { value: "GARVIT TUTEJA", label: "GARVIT TUTEJA", batch: "9" },
  { value: "HARSH RANJAN", label: "HARSH RANJAN", batch: "9" },
  { value: "HRIDYA JAIN", label: "HRIDYA JAIN", batch: "9" },
  { value: "JENI LADANI", label: "JENI LADANI", batch: "9" },
  { value: "LAKSHITA PABRI", label: "LAKSHITA PABRI", batch: "9" },
  { value: "MANAS VERMA", label: "MANAS VERMA", batch: "9" },
  { value: "MOHD MUZAMMIL", label: "MOHD MUZAMMIL", batch: "9" },
  { value: "RAKSHITA LOHIA", label: "RAKSHITA LOHIA", batch: "9" },
  { value: "RIYA THAKRAN", label: "RIYA THAKRAN", batch: "9" },
  { value: "ROHIT GUPTA", label: "ROHIT GUPTA", batch: "9" },
  { value: "SAATWIK SHEORAN", label: "SAATWIK SHEORAN", batch: "9" },
  { value: "SIDHI LOHIYA", label: "SIDHI LOHIYA", batch: "9" },
  { value: "TALLURI SHARVARISH", label: "TALLURI SHARVARISH", batch: "9" },
  { value: "VASHU SAINI", label: "VASHU SAINI", batch: "9" },
  { value: "YASH VARDHAN", label: "YASH VARDHAN", batch: "9" },

  // Batch 10
  { value: "AKANSHA CHAUDHARY", label: "AKANSHA CHAUDHARY", batch: "10" },
  { value: "AKSHIT MATTA", label: "AKSHIT MATTA", batch: "10" },
  { value: "KIYANA IRANI", label: "KIYANA IRANI", batch: "10" },
  { value: "KUNAL THAKUR", label: "KUNAL THAKUR", batch: "10" },
  { value: "NAVIN CHAUDHARY", label: "NAVIN CHAUDHARY", batch: "10" },
  { value: "NIVEDIYA SINGH", label: "NIVEDIYA SINGH", batch: "10" },
  { value: "RITIKA MADAN", label: "RITIKA MADAN", batch: "10" },
  { value: "SAKETH REDDY", label: "SAKETH REDDY", batch: "10" },
  { value: "SAMKIT JAIN", label: "SAMKIT JAIN", batch: "10" },
  { value: "SHASHVAT BHADLA", label: "SHASHVAT BHADLA", batch: "10" },
  { value: "TANYA TOMAR", label: "TANYA TOMAR", batch: "10" },
  { value: "UTKARSH KUMAR", label: "UTKARSH KUMAR", batch: "10" },
  { value: "VIVAAN FERNANDES", label: "VIVAAN FERNANDES", batch: "10" },
  { value: "YURENA", label: "YURENA", batch: "10" },

  // Batch 11
  { value: "AVISHI AGARWAL", label: "AVISHI AGARWAL", batch: "11" },
  { value: "DAKSH VERMA", label: "DAKSH VERMA", batch: "11" },
  { value: "HARSH HITESH UGANI", label: "HARSH HITESH UGANI", batch: "11" },
  { value: "HET SHIRSEKAR", label: "HET SHIRSEKAR", batch: "11" },
  { value: "MANSURI MOHAMED WARIS", label: "MANSURI MOHAMED WARIS", batch: "11" },
  { value: "NITYA JAIN", label: "NITYA JAIN", batch: "11" },
  { value: "PALAK RUPESH RATHI", label: "PALAK RUPESH RATHI", batch: "11" },
  { value: "POPAT HET DEVENBHAI", label: "POPAT HET DEVENBHAI", batch: "11" },
  { value: "PRASAD B V", label: "PRASAD B V", batch: "11" },
  { value: "PRITHVIRAJ SINGH RATHORE", label: "PRITHVIRAJ SINGH RATHORE", batch: "11" },
  { value: "RAUNEET SHEKHAR", label: "RAUNEET SHEKHAR", batch: "11" },
  { value: "SARUGURU UJJAIN RAJ", label: "SARUGURU UJJAIN RAJ", batch: "11" },
  { value: "VAISHNAVI KESARI", label: "VAISHNAVI KESARI", batch: "11" },
  { value: "VUPPU SIDDHARTH", label: "VUPPU SIDDHARTH", batch: "11" },
  { value: "YASH PRAVIN SALVI", label: "YASH PRAVIN SALVI", batch: "11" }
];




// ─────────────────── LOCATIONS ──────────────────
export const fromLocations = [
  { value: "VIKG", label: "VIKG" },
  { value: "VIKG NEEMUCH", label: "VIKG NEEMUCH" },
  { value: "VIKG VIKO", label: "VIKG VIKO" },
  { value: "VIKG MANDSAUR", label: "VIKG MANDSAUR" },
  { value: "VIKG SEEKAR", label: "VIKG SEEKAR" },
  { value: "VIKG RANTHAMBORE", label: "VIKG RANTHAMBORE" },
];

export const toLocations = [
  { value: "VIKG", label: "VIKG" },
  { value: "MANDSAUR", label: "MANDSAUR" },
  { value: "NEEMUCH", label: "NEEMUCH" },
  { value: "VIKG", label: "VIKG" }
];

// ────────────────────────────────────────────────

// ------------------------STUDENTS------------------------




export const students = [
  { value: "SHARIQ ALI", label: "SHARIQ ALI" },
  { value: "RUSHIKESH VIKAS JALKOTE", label: "RUSHIKESH VIKAS JALKOTE" },
  { value: "PANKHURI SAXENA", label: "PANKHURI SAXENA" },
  { value: "SURYANSH MISHRA", label: "SURYANSH MISHRA" },
  { value: "DIGVIJAY SHEKHAWAT", label: "DIGVIJAY SHEKHAWAT" },
  { value: "KV TARUN", label: "KV TARUN" },
  { value: "NABAJIT MALLIK", label: "NABAJIT MALLIK" },
  { value: "FAHAD", label: "FAHAD" },
  { value: "MOHD ARFIN", label: "MOHD ARFIN" },
  { value: "AYUSH RAJ", label: "AYUSH RAJ" },
  { value: "MOHAK PARMAR", label: "MOHAK PARMAR" },
  { value: "PARTH MISHRA", label: "PARTH MISHRA" },
  { value: "JEROME PATRICK PAUL JERARD", label: "JEROME PATRICK PAUL JERARD" },
  { value: "ASHUTOSH SHARMA", label: "ASHUTOSH SHARMA" },
  { value: "TAPAN SIR", label: "TAPAN SIR" },
  { value: "TANISH SIR", label: "TANISH SIR" },
  { value: "GURYOG SIR", label: "GURYOG SIR" },
  { value: "YUVRAJ DASHORA", label: "YUVRAJ DASHORA" },
  { value: "JATIN GHANGAS", label: "JATIN GHANGAS" },
  { value: "SIDDHI POOJARY", label: "SIDDHI POOJARY" },
  { value: "SURESH KAURANI", label: "SURESH KAURANI" },
  { value: "SHEEBA", label: "SHEEBA" },
  { value: "ANURAG SHARMA", label: "ANURAG SHARMA" },
  { value: "MAHESH CHANDRA SHARMA", label: "MAHESH CHANDRA SHARMA" },
  { value: "SHUBHAM VERMA", label: "SHUBHAM VERMA" },
  // =========================STUDENTS===========================
  // Batch 1
  { value: "ANIRUDH BORA", label: "ANIRUDH BORA", batch: "1" },
  { value: "APEKSHA SHARMA", label: "APEKSHA SHARMA", batch: "1" },
  { value: "BHARGAVI BHARDWAJ", label: "BHARGAVI BHARDWAJ", batch: "1" },
  { value: "DEVANSH SINGH BAIS", label: "DEVANSH SINGH BAIS", batch: "1" },
  { value: "DILSHAD NAVSHAD IDRISI", label: "DILSHAD NAVSHAD IDRISI", batch: "1" },
  { value: "DRISHA MODI", label: "DRISHA MODI", batch: "1" },
  { value: "GOURAV GAUTAM", label: "GOURAV GAUTAM", batch: "1" },
  { value: "HARDIK AGARWAL", label: "HARDIK AGARWAL", batch: "1" },
  { value: "HARSHITA BATRA", label: "HARSHITA BATRA", batch: "1" },
  { value: "HARSHITA NARU", label: "HARSHITA NARU", batch: "1" },
  { value: "ISHITA BHARDWAJ", label: "ISHITA BHARDWAJ", batch: "1" },
  { value: "JAI DEV PRATAP SINGH", label: "JAI DEV PRATAP SINGH", batch: "1" },
  { value: "JANVI BALWANI", label: "JANVI BALWANI", batch: "1" },
  { value: "JEREMY JOHN", label: "JEREMY JOHN", batch: "1" },
  { value: "KASHISH SANTOSH CHAUDHARY", label: "KASHISH SANTOSH CHAUDHARY", batch: "1" },
  { value: "LAKSHYA SETHI", label: "LAKSHYA SETHI", batch: "1" },
  { value: "MANSI CHOUDHARY", label: "MANSI CHOUDHARY", batch: "1" },
  { value: "NIKHIL SHARMA", label: "NIKHIL SHARMA", batch: "1" },
  { value: "OM ARORA", label: "OM ARORA", batch: "1" },
  { value: "PARTH PAPNEJA", label: "PARTH PAPNEJA", batch: "1" },
  { value: "PRACHI GUPTA", label: "PRACHI GUPTA", batch: "1" },
  { value: "PREM KUMAR", label: "PREM KUMAR", batch: "1" },
  { value: "PRIYANSHI YADAV", label: "PRIYANSHI YADAV", batch: "1" },
  { value: "PURUHANS", label: "PURUHANS", batch: "1" },
  { value: "PURVANSHI GUPTA", label: "PURVANSHI GUPTA", batch: "1" },
  { value: "RISHABH SINDHU", label: "RISHABH SINDHU", batch: "1" },
  { value: "RIYA MANGLANI", label: "RIYA MANGLANI", batch: "1" },
  { value: "ROMIN GOSWAMI", label: "ROMIN GOSWAMI", batch: "1" },
  { value: "SAHIL BACHHAWAT", label: "SAHIL BACHHAWAT", batch: "1" },
  { value: "SAMEER KUMAR YADAV", label: "SAMEER KUMAR YADAV", batch: "1" },
  { value: "SARTAJ GULZAR", label: "SARTAJ GULZAR", batch: "1" },
  { value: "SARTHAK MEHROTRA", label: "SARTHAK MEHROTRA", batch: "1" },
  { value: "SATYAM PESWANI", label: "SATYAM PESWANI", batch: "1" },
  { value: "SHARDUL SETH", label: "SHARDUL SETH", batch: "1" },
  { value: "SHAURYA SINGH", label: "SHAURYA SINGH", batch: "1" },
  { value: "TANISH KASWAN NAYASAR", label: "TANISH KASWAN NAYASAR", batch: "1" },
  { value: "TEJAS BHATIA", label: "TEJAS BHATIA", batch: "1" },
  { value: "TRIJAL KUMAR", label: "TRIJAL KUMAR", batch: "1" },
  { value: "UTKARSH SRIVASTAVA", label: "UTKARSH SRIVASTAVA", batch: "1" },
  { value: "VAIBHAV GARG", label: "VAIBHAV GARG", batch: "1" },
  { value: "VALLABH AMBADAS UMALE", label: "VALLABH AMBADAS UMALE", batch: "1" },
  { value: "VEDANT GYANCHANDANI", label: "VEDANT GYANCHANDANI", batch: "1" },
  { value: "VIJAY SAHU", label: "VIJAY SAHU", batch: "1" },
  { value: "VIVAAN KASHYAP", label: "VIVAAN KASHYAP", batch: "1" },
  { value: "VRINDA JHURIA", label: "VRINDA JHURIA", batch: "1" },

  // Batch 2
  { value: "ABHYUDAY KUMAWAT", label: "ABHYUDAY KUMAWAT", batch: "2" },
  { value: "ADITYA SINGH", label: "ADITYA SINGH", batch: "2" },
  { value: "AMAN AHMED", label: "AMAN AHMED", batch: "2" },
  { value: "ARNAV SETH", label: "ARNAV SETH", batch: "2" },
  { value: "ASMIT RAWAT", label: "ASMIT RAWAT", batch: "2" },
  { value: "AYUSH AJAY", label: "AYUSH AJAY", batch: "2" },
  { value: "DIYA JAIN", label: "DIYA JAIN", batch: "2" },
  { value: "GAURAV KHANNA", label: "GAURAV KHANNA", batch: "2" },
  { value: "JAYNIT JAIN", label: "JAYNIT JAIN", batch: "2" },
  { value: "PRASOON MATHUR", label: "PRASOON MATHUR", batch: "2" },
  { value: "PRIYANSHI KUMAR", label: "PRIYANSHI KUMAR", batch: "2" },
  { value: "RAGHAV DWIVEDI", label: "RAGHAV DWIVEDI", batch: "2" },
  { value: "SANI MALIK", label: "SANI MALIK", batch: "2" },
  { value: "SHRUTI KUMARI", label: "SHRUTI KUMARI", batch: "2" },
  { value: "SNEHA JAUHARI", label: "SNEHA JAUHARI", batch: "2" },
  { value: "TANVEER SINGH ANEJA", label: "TANVEER SINGH ANEJA", batch: "2" },
  // Batch 3
  { value: "ADESH KUMAR YADAV", label: "ADESH KUMAR YADAV", batch: "3" },
  { value: "ANTRA KATOCH", label: "ANTRA KATOCH", batch: "3" },
  { value: "ASHMAN SINGH SANDHU", label: "ASHMAN SINGH SANDHU", batch: "3" },
  { value: "BHANU PRATAP SINGH", label: "BHANU PRATAP SINGH", batch: "3" },
  { value: "BHARAT DHAKAR", label: "BHARAT DHAKAR", batch: "3" },
  { value: "CHAVI SAXENA", label: "CHAVI SAXENA", batch: "3" },
  { value: "DEVEN SHARMA", label: "DEVEN SHARMA", batch: "3" },
  { value: "DISHA THAKKAR", label: "DISHA THAKKAR", batch: "3" },
  { value: "EKLAVYA SINGH", label: "EKLAVYA SINGH", batch: "3" },
  { value: "HIR PATEL", label: "HIR PATEL", batch: "3" },
  { value: "JAYAGANESAN S", label: "JAYAGANESAN S", batch: "3" },
  { value: "NANDAN VACHHANI", label: "NANDAN VACHHANI", batch: "3" },
  { value: "NAVYYA MAKIN", label: "NAVYYA MAKIN", batch: "3" },
  { value: "NIKHIL GOEL", label: "NIKHIL GOEL", batch: "3" },
  { value: "PARV TAYAL", label: "PARV TAYAL", batch: "3" },
  { value: "PRIYANSHU SINGHAL", label: "PRIYANSHU SINGHAL", batch: "3" },
  { value: "RAJAT MEENA", label: "RAJAT MEENA", batch: "3" },
  { value: "RIYA SUTHAR", label: "RIYA SUTHAR", batch: "3" },
  { value: "SAIYAM CHAKRAVERTY", label: "SAIYAM CHAKRAVERTY", batch: "3" },
  { value: "SAMRUDDHA SHETE", label: "SAMRUDDHA SHETE", batch: "3" },
  { value: "SAYONI AGARWAL", label: "SAYONI AGARWAL", batch: "3" },
  { value: "SHIVANI UDAR", label: "SHIVANI UDAR", batch: "3" },
  { value: "SIDNEY FERNANDES", label: "SIDNEY FERNANDES", batch: "3" },
  { value: "TANU PRIYA", label: "TANU PRIYA", batch: "3" },

  // Batch 4
  { value: "AMAN KUMAR DALAL", label: "AMAN KUMAR DALAL", batch: "4" },
  { value: "DIVYANSH", label: "DIVYANSH", batch: "4" },
  { value: "ISHA RATHOD", label: "ISHA RATHOD", batch: "4" },
  { value: "JAI SHARMA", label: "JAI SHARMA", batch: "4" },
  { value: "KESHAV SHARMA", label: "KESHAV SHARMA", batch: "4" },
  { value: "KOMARAVELLI ROSHAN", label: "KOMARAVELLI ROSHAN", batch: "4" },
  { value: "KUNAL CHOUDHARY", label: "KUNAL CHOUDHARY", batch: "4" },
  { value: "MOHD NAWAZ", label: "MOHD NAWAZ", batch: "4" },
  { value: "PARAS RADHENAGAR", label: "PARAS RADHENAGAR", batch: "4" },
  { value: "PREM", label: "PREM", batch: "4" },
  { value: "SAKSHI SOLANKI", label: "SAKSHI SOLANKI", batch: "4" },
  { value: "SANEHI NAYAK", label: "SANEHI NAYAK", batch: "4" },
  { value: "SRUSHTI ABHAY", label: "SRUSHTI ABHAY", batch: "4" },
  { value: "YASH JINDAL", label: "YASH JINDAL", batch: "4" },

  // Batch 5
  { value: "ANJALI ADHIKARI", label: "ANJALI ADHIKARI", batch: "5" },
  { value: "ANSHPREET SINGH", label: "ANSHPREET SINGH", batch: "5" },
  { value: "ANUSH BAGRODIA", label: "ANUSH BAGRODIA", batch: "5" },
  { value: "ARJUN SHUKLA", label: "ARJUN SHUKLA", batch: "5" },
  { value: "GANGA SINGH", label: "GANGA SINGH", batch: "5" },
  { value: "MANAV", label: "MANAV", batch: "5" },
  { value: "MAYANK CHOUDHARY", label: "MAYANK CHOUDHARY", batch: "5" },
  { value: "MAYANK PURI", label: "MAYANK PURI", batch: "5" },
  { value: "RASHI SINGH", label: "RASHI SINGH", batch: "5" },
  { value: "SHASHANK SINGH PARIHAR", label: "SHASHANK SINGH PARIHAR", batch: "5" },
  { value: "SHIVAM MAHAJAN", label: "SHIVAM MAHAJAN", batch: "5" },
  { value: "SOURABH SETHI", label: "SOURABH SETHI", batch: "5" },
  { value: "UBEAID SHAIKH", label: "UBEAID SHAIKH", batch: "5" },
  { value: "YASH YADAV", label: "YASH YADAV", batch: "5" },
  { value: "YASHITA NAGAR", label: "YASHITA NAGAR", batch: "5" },

  // Batch 6
  { value: "AASHTA SHARAMA", label: "AASHTA SHARAMA", batch: "6" },
  { value: "ADIT UPPINI", label: "ADIT UPPINI", batch: "6" },
  { value: "AJEET SINGH", label: "AJEET SINGH", batch: "6" },
  { value: "AKSHAT AGARWAL", label: "AKSHAT AGARWAL", batch: "6" },
  { value: "ARSHPREET", label: "ARSHPREET", batch: "6" },
  { value: "ASHISH BISHNOI", label: "ASHISH BISHNOI", batch: "6" },
  { value: "ATISHAY", label: "ATISHAY", batch: "6" },
  { value: "DAKSHIKA SHARMA", label: "DAKSHIKA SHARMA", batch: "6" },
  { value: "DIVYANSH SINGH", label: "DIVYANSH SINGH", batch: "6" },
  { value: "JAI DESAI", label: "JAI DESAI", batch: "6" },
  { value: "KUNAL MEENA", label: "KUNAL MEENA", batch: "6" },
  { value: "M MANNO GANESAN", label: "M MANNO GANESAN", batch: "6" },
  { value: "MEHAK ARCHRIYA", label: "MEHAK ARCHRIYA", batch: "6" },
  { value: "NIKHIL VAISHNAV", label: "NIKHIL VAISHNAV", batch: "6" },
  { value: "SHRUTI SINGH", label: "SHRUTI SINGH", batch: "6" },
  { value: "SHUBHAM BIST", label: "SHUBHAM BIST", batch: "6" },
  { value: "SUKRIT SINGH", label: "SUKRIT SINGH", batch: "6" },
  { value: "VEDANT MOHAN", label: "VEDANT MOHAN", batch: "6" },
  { value: "VIDHI VIVEK", label: "VIDHI VIVEK", batch: "6" },
  { value: "YAJAT TAK", label: "YAJAT TAK", batch: "6" },

  // Batch 7
  { value: "ANIMESH", label: "ANIMESH", batch: "7" },
  { value: "ARYAMAN", label: "ARYAMAN", batch: "7" },
  { value: "BHARAT", label: "BHARAT", batch: "7" },
  { value: "DIVYANSH KHARI", label: "DIVYANSH KHARI", batch: "7" },
  { value: "DIYA PATEL", label: "DIYA PATEL", batch: "7" },
  { value: "HARDIK WASSON", label: "HARDIK WASSON", batch: "7" },
  { value: "HUSSAIN", label: "HUSSAIN", batch: "7" },
  { value: "JIGYASA", label: "JIGYASA", batch: "7" },
  { value: "KESHIKA CHHETRI", label: "KESHIKA CHHETRI", batch: "7" },
  { value: "KURAPATI MAANVIE", label: "KURAPATI MAANVIE", batch: "7" },
  { value: "MINI SHARMA", label: "MINI SHARMA", batch: "7" },
  { value: "MOHAK", label: "MOHAK", batch: "7" },
  { value: "MOHD KAIS", label: "MOHD KAIS", batch: "7" },
  { value: "PAKSH", label: "PAKSH", batch: "7" },
  { value: "PIYUSH", label: "PIYUSH", batch: "7" },
  { value: "PRABHJOT", label: "PRABHJOT", batch: "7" },
  { value: "RAHUL SHARMA", label: "RAHUL SHARMA", batch: "7" },
  { value: "RASKAR KETAKI", label: "RASKAR KETAKI", batch: "7" },
  { value: "RISHABH SINGH", label: "RISHABH SINGH", batch: "7" },
  { value: "RIYA VATS", label: "RIYA VATS", batch: "7" },
  { value: "RUDRAPRIYA", label: "RUDRAPRIYA", batch: "7" },
  { value: "SANDESH", label: "SANDESH", batch: "7" },
  // Batch 8
  { value: "ANSH PREET BALI", label: "ANSH PREET BALI", batch: "8" },
  { value: "AUSTRAL", label: "AUSTRAL", batch: "8" },
  { value: "JATIN DAGAR", label: "JATIN DAGAR", batch: "8" },
  { value: "MEHUL", label: "MEHUL", batch: "8" },
  { value: "MINAKSHI YADAV", label: "MINAKSHI YADAV", batch: "8" },
  { value: "RADHIKA JAIN", label: "RADHIKA JAIN", batch: "8" },
  { value: "ROHAK JAIN", label: "ROHAK JAIN", batch: "8" },
  { value: "SHUBHAM AGARWAL", label: "SHUBHAM AGARWAL", batch: "8" },
  { value: "VARUN SINHA", label: "VARUN SINHA", batch: "8" },
  { value: "YASH BANSAL", label: "YASH BANSAL", batch: "8" },
  { value: "YASH MISHRA", label: "YASH MISHRA", batch: "8" },

  // Batch 9
  { value: "ANIRUDH SINGH", label: "ANIRUDH SINGH", batch: "9" },
  { value: "ANMOL SINGH", label: "ANMOL SINGH", batch: "9" },
  { value: "AYUSH WABLE", label: "AYUSH WABLE", batch: "9" },
  { value: "GARVIT TUTEJA", label: "GARVIT TUTEJA", batch: "9" },
  { value: "HARSH RANJAN", label: "HARSH RANJAN", batch: "9" },
  { value: "HRIDYA JAIN", label: "HRIDYA JAIN", batch: "9" },
  { value: "JENI LADANI", label: "JENI LADANI", batch: "9" },
  { value: "LAKSHITA PABRI", label: "LAKSHITA PABRI", batch: "9" },
  { value: "MANAS VERMA", label: "MANAS VERMA", batch: "9" },
  { value: "MOHD MUZAMMIL", label: "MOHD MUZAMMIL", batch: "9" },
  { value: "RAKSHITA LOHIA", label: "RAKSHITA LOHIA", batch: "9" },
  { value: "RIYA THAKRAN", label: "RIYA THAKRAN", batch: "9" },
  { value: "ROHIT GUPTA", label: "ROHIT GUPTA", batch: "9" },
  { value: "SAATWIK SHEORAN", label: "SAATWIK SHEORAN", batch: "9" },
  { value: "SIDHI LOHIYA", label: "SIDHI LOHIYA", batch: "9" },
  { value: "TALLURI SHARVARISH", label: "TALLURI SHARVARISH", batch: "9" },
  { value: "VASHU SAINI", label: "VASHU SAINI", batch: "9" },
  { value: "YASH VARDHAN", label: "YASH VARDHAN", batch: "9" },

  // Batch 10
  { value: "AKANSHA CHAUDHARY", label: "AKANSHA CHAUDHARY", batch: "10" },
  { value: "AKSHIT MATTA", label: "AKSHIT MATTA", batch: "10" },
  { value: "KIYANA IRANI", label: "KIYANA IRANI", batch: "10" },
  { value: "KUNAL THAKUR", label: "KUNAL THAKUR", batch: "10" },
  { value: "NAVIN CHAUDHARY", label: "NAVIN CHAUDHARY", batch: "10" },
  { value: "NIVEDIYA SINGH", label: "NIVEDIYA SINGH", batch: "10" },
  { value: "RITIKA MADAN", label: "RITIKA MADAN", batch: "10" },
  { value: "SAKETH REDDY", label: "SAKETH REDDY", batch: "10" },
  { value: "SAMKIT JAIN", label: "SAMKIT JAIN", batch: "10" },
  { value: "SHASHVAT BHADLA", label: "SHASHVAT BHADLA", batch: "10" },
  { value: "TANYA TOMAR", label: "TANYA TOMAR", batch: "10" },
  { value: "UTKARSH KUMAR", label: "UTKARSH KUMAR", batch: "10" },
  { value: "VIVAAN FERNANDES", label: "VIVAAN FERNANDES", batch: "10" },
  { value: "YURENA", label: "YURENA", batch: "10" },

  // Batch 11
  { value: "AVISHI AGARWAL", label: "AVISHI AGARWAL", batch: "11" },
  { value: "DAKSH VERMA", label: "DAKSH VERMA", batch: "11" },
  { value: "HARSH HITESH UGANI", label: "HARSH HITESH UGANI", batch: "11" },
  { value: "HET SHIRSEKAR", label: "HET SHIRSEKAR", batch: "11" },
  { value: "MANSURI MOHAMED WARIS", label: "MANSURI MOHAMED WARIS", batch: "11" },
  { value: "NITYA JAIN", label: "NITYA JAIN", batch: "11" },
  { value: "PALAK RUPESH RATHI", label: "PALAK RUPESH RATHI", batch: "11" },
  { value: "POPAT HET DEVENBHAI", label: "POPAT HET DEVENBHAI", batch: "11" },
  { value: "PRASAD B V", label: "PRASAD B V", batch: "11" },
  { value: "PRITHVIRAJ SINGH RATHORE", label: "PRITHVIRAJ SINGH RATHORE", batch: "11" },
  { value: "RAUNEET SHEKHAR", label: "RAUNEET SHEKHAR", batch: "11" },
  { value: "SARUGURU UJJAIN RAJ", label: "SARUGURU UJJAIN RAJ", batch: "11" },
  { value: "VAISHNAVI KESARI", label: "VAISHNAVI KESARI", batch: "11" },
  { value: "VUPPU SIDDHARTH", label: "VUPPU SIDDHARTH", batch: "11" },
  { value: "YASH PRAVIN SALVI", label: "YASH PRAVIN SALVI", batch: "11" }
];